### PR TITLE
Create tracker.json

### PR DESCRIPTION
**Pull request by rsnodgrass**
Add support for custom_updater to automatically update/download latest version to Home Assistant
See https://github.com/custom-components/custom_updater

### CODE REVIEW

**Comment by thomasloven** [comment]
There's a special clause in the custom_updater which looks through my github repositories and adds anything that starts with `lovelace-`. It's always been there. *All* my cards have *always* been supported by custom_updater. So much, in fact, that if I make a card with the same name as one that already exists, mine takes precedence.

**Comment by thomasloven** [comment]
But thank you very much for your interest in making things better for everyone!

**Comment by rsnodgrass** [comment]
Thanks for the speedy response!

Hmmm, interesting.  I looked through the custom_updater code and couldn't
find anything in either the code or configuration about which repositories
it searches "automagically".

https://github.com/custom-components/custom_updater/blob/master/custom_components/custom_updater.py

Ok...ignore my suggestion then ;)  Thought it certainly would be more
explicit to have a custom_updater.json files in the repositories (or a
shared repository), rather than magic repositories existing.  Of course, I
think that custom_updater should just pull the update information from the
actual already installed code rather than requiring everyone to manually
configure in their configuration.yaml (in that case it should just be when
needing to override).

Ryan

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by thomasloven** [comment]
It's hidden away in the script that updates the tracking information for pyupdate - a python module requisite for the custom_updater component. It was actually added by @luddeeus because I wouldn't get my lazy ass off the cart and add my things to the [custom-cards](https://github.com/custom-cards) organization ...

**Comment by thomasloven** [comment]
If you have an old version of custom_updater, adding a version number to the url when importing my cards will get the updates to work. With the latest versions it should be automatic from the start - especially if you use `/customcards/` rather than `/local`.

**Pull request closed without merging**
